In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5,6])
arr2.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [7]:
np.arange(0,10,2).reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4)) #use in Deep learning 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
##identity matrix arrays
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
#attributes of numpy
print(arr1.ndim)
print(arr1.size)
print(arr1.itemsize)

1
5
4


In [20]:
##Numpy Vectorized operations
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])


##Element wise Addition
print("Addition : ",arr1+arr2)

## Element Wise Subtraction
print("subtraction : ",arr2-arr1)

##simillarly we can do multiplication and division okay


Addition :  [11 22 33 44 55]
subtraction :  [ 9 18 27 36 45]


In [25]:
#Universal Function

arr = np.array([2,3,4,5,6])

#Squreroot
print(np.sqrt(arr))

#Exponential
print(np.exp(arr))

#sine
print(np.sin(arr))

#Natural Log
print(np.log(arr))


[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
#Array Slicing and indexing

arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)

arr[0]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([1, 2, 3, 4])

In [39]:
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [41]:
arr[1:,2:]  #Remember this thing and preactice because it it very much easy

array([[ 7,  8],
       [11, 12]])

In [42]:
## Modify Array Element
arr[0,0] = 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [44]:
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [48]:
#statical concept - normalization

data = np.array([1,2,3,4,5])

mean = np.mean(data)
print(mean)

#aslo calculate median and mode and variance simillarly 


std_dev = np.std(data)
print(std_dev)


#Normalized the data
normalized_data = (data-mean) / std_dev
print("Normalized Data : ", normalized_data)

3.0
1.4142135623730951
Normalized Data :  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [49]:
#logical Operations
data = np.array([1,2,3,4,5,6,7,8,9,10])
data>5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [50]:
data[data>5]

array([ 6,  7,  8,  9, 10])

In [52]:
data[(data>5) & (data < 8)]


array([6, 7])