In [3]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
print(arr1.ndim)

1


In [4]:
arr2 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr2.ndim)

2


In [5]:
arr3 = np.array([1,2,3,4,5],ndmin=10)
print(arr3)
print(arr3.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


In [6]:
#create numpy array using function

In [7]:
#zeroes

In [8]:
arr_zero = np.zeros(4) #one dimensional array
arr_zero2 = np.zeros((3,4))  # get 3*4 array
print(arr_zero)
print(arr_zero2)

[0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
#ones

In [10]:
arr_one = np.ones(5) 
print(arr_one)

[1. 1. 1. 1. 1.]


In [11]:
#Empty Array

In [12]:
aee_empty = np.empty(5)
print(aee_empty)

[1. 1. 1. 1. 1.]


In [13]:
#Range

In [14]:
ar_rn = np.arange(4)
print(ar_rn)

[0 1 2 3]


In [15]:
#diagonal

In [16]:
arr_dia = np.eye(3)
print(arr_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
#random

In [18]:
#Rand()
var = np.random.rand(5)
print(var)

[0.02319523 0.34894099 0.83032287 0.6190072  0.09318746]
